### ISSUE TITLE
Miri flag passing changed

### ISSUE THREAD

**Issue by RalfJung** [sunjay/pea#6]
`cargo miri test` changed to be more compatible with `cargo test`, but this means we had to find a different way to pass flags to the interpreter, so there now is a `MIRIFLAGS` environment variable for that. The old way still works for now, but is deprecated.

This affects the following line:
https://github.com/sunjay/pea/blob/5790955b700e4757291e00c6a92fbc61ea9046bc/azure-pipelines.yml#L86
This should now be `MIRIFLAGS="-Zmiri-disable-isolation" cargo miri test --verbose --all`. `cargo miri setup` is also not needed any more.

**Comment by sunjay** [comment]
Thanks @RalfJung! I've fixed that in https://github.com/sunjay/pea/commit/7551d0cb9ec9d2980219d4cc009eb35a82dd74e0.
